# ============================================================================
# ThreadKeeper — Automated Release Pipeline
#
# Trigger: Push a version tag (e.g. "git tag v0.3.0 && git push --tags")
#
# What it does:
#   1. Builds Windows .exe installer (NSIS) on ubuntu via wine
#   2. Builds macOS .dmg installer on macos runner
#   3. Creates a GitHub Release with both installers attached
#   4. Auto-generates release notes from commits since last tag
#
# Usage:
#   1. Bump version in package.json (e.g. "0.3.0")
#   2. git add package.json && git commit -m "v0.3.0"
#   3. git tag v0.3.0
#   4. git push origin main --tags
#   5. GitHub Actions does the rest!
# ============================================================================

name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on v0.3.0, v1.0.0, etc.

permissions:
  contents: write  # Needed to create releases and upload assets

jobs:
  # ── Build Windows installer ──────────────────────────────────────────────
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Build Windows installer
        run: npx electron-builder --win --publish never

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: release/*.exe
          retention-days: 1

  # ── Build macOS installer ────────────────────────────────────────────────
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Build macOS installer
        run: npx electron-builder --mac --publish never

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-installer
          path: release/*.dmg
          retention-days: 1

  # ── Create GitHub Release ────────────────────────────────────────────────
  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for release notes

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: ./artifacts

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-installer
          path: ./artifacts

      - name: List artifacts
        run: ls -la ./artifacts/

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "ThreadKeeper v${{ steps.version.outputs.VERSION }}"
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./artifacts/*.exe
            ./artifacts/*.dmg
